---
- hosts: dev
  tasks:
    - name: installation apache webserver    
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: start server
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Copy file index.html (customising)
      ansible.builtin.copy:
        src: /etc/ansible/playbooks/index.html
        dest: /var/www/html/
    
    - name: changing the port number
      ansible.builtin.template:
         src: /etc/ansible/playbooks/httpd.conf.j2
         dest: /etc/httpd/conf/httpd.conf
      vars:
        port: 90
      notify:
      - Restart Apache
  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: httpd
        state: restarted
             
    
    
